name: Build

on:
  workflow_call:

jobs:
  install:
    name: Install
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["install"]'

  complement:
    name: Complement Testee
    uses: ./.github/workflows/bake.yml
    needs: [install]
    with:
      bake_targets: '["complement-testee"]'

  pkgdeb:
    if: false
    name: Pkg Deb
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["pkg-deb"]'
      cargo_profiles: '["test", "bench"]'
      feat_sets: '["all"]'
      rust_toolchains: '["stable"]'
