name: Build

on:
  workflow_call:

jobs:
  install:
    name: Install
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["install"]'

  complement:
    name: Complement Testee
    uses: ./.github/workflows/bake.yml
    needs: [install]
    with:
      bake_targets: '["complement-testee"]'
