name: Dependencies

on:
  workflow_call:

jobs:
  systems:
    name: System
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["systems"]'

  buildsys:
    name: Builder
    needs: [systems]
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["buildsys"]'

  tester:
    name: Tester
    needs: [systems]
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["complement-tester"]'

  sources:
    name: Acquire
    needs: [buildsys]
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["sources"]'

  rocksdb:
    name: RocksDB
    needs: [sources]
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["rocksdb"]'

  deps:
    if: false
    name: Build
    needs: [rocksdb]
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["deps-clippy", "deps-build-tests", "deps-build-bins"]'
