name: Docker Images

on:
  workflow_call:
    inputs:
      id:
        type: string
        description: Dockerhub acct/repo identity.
      url:
        type: string
        description: Git repository for checkout.
      commands:
        type: string
        required: false
        default: '["check"]'
        description: Cargo command vector
      profiles:
        type: string
        required: false
        default: '["dev"]'
        description: Cargo profile vector
      features:
        type: string
        required: false
        default: '["--features=default"]'
        description: Cargo feature vector
      toolchains:
        type: string
        required: false
        default: '["+nightly"]'
        description: Rust toolchain vector
      systems:
        type: string
        required: false
        default: '["ubuntu-24.10"]'
        description: Operation system distribution vector
      machines:
        type: string
        required: false
        default: '["x86_64"]'
        description: Hardware platform vector
      test:
        type: boolean
        required: false
        default: false
        description: Echo all docker commands rather than invoking them.

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: false

env:
  uwu_id: ${{inputs.id}}
  uwu_url: ${{inputs.url}}

jobs:
  bake:
    runs-on: ${{matrix.machine}}
    strategy:
      fail-fast: false
      matrix:
        command: ${{fromJSON(inputs.commands)}}
        profile: ${{fromJSON(inputs.profiles)}}
        feature: ${{fromJSON(inputs.features)}}
        toolchain: ${{fromJSON(inputs.toolchains)}}
        system: ${{fromJSON(inputs.systems)}}
        machine: ${{fromJSON(inputs.machines)}}

    steps:
    - uses: actions/checkout@v3
    - name: build
      env:
        uwu_commands: ${{matrix.command}}
        uwu_profiles: ${{matrix.profile}}
        uwu_features: ${{matrix.feature}}
        uwu_toolchains: ${{matrix.toolchain}}
        uwu_systems: ${{matrix.system}}
        uwu_machines: ${{matrix.machine}}
        uwu_test: ${{inputs.test}}

      run: |
        echo "ok"
        #docker/docker.sh
