name: Linting

on:
  workflow_call:

jobs:
  fmt:
    name: Format
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["fmt"]'
      cargo_profiles: '["test"]'
      feat_sets: '["none"]'
      rust_toolchains: '["nightly"]'

  audit:
    name: Audit
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["audit"]'
      cargo_profiles: '["test"]'
      feat_sets: '["none"]'
      rust_toolchains: '["nightly"]'

  lychee:
    name: Lychee
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["lychee"]'
      cargo_profiles: '["test"]'
      feat_sets: '["none"]'
      rust_toolchains: '["nightly"]'

  clippy:
    name: Clippy
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["clippy"]'

  doc:
    name: Docs
    needs: [clippy]
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["docs"]'
      cargo_profiles: '["test"]'
      rust_toolchains: '["nightly"]'
