name: Publish

on:
  workflow_call:
    secrets:
      ghcr_token:
      dockerhub_token:
    inputs:
      cargo_profiles:
        type: string
        description: Cargo profiles
      feat_sets:
        type: string
        description: Cargo feature groups
      rust_toolchains:
        type: string
        description: Rust toolchains
      sys_names:
        type: string
        description: System names
      sys_versions:
        type: string
        description: System versions
      rust_targets:
        type: string
        description: Rust targets
      sys_targets:
        type: string
        description: System targets
      machines:
        type: string
        description: Hardware platform vector
      excludes:
        type: string
        default: '[]'
        description: Matrix exclusions
      includes:
        type: string
        default: '[]'
        description: Matrix inclusions
      docker_repo:
        type: string
        description: DockerHub Repository
      release_url:
        type: string
        description: For release assets

jobs:
  documents:
    if: >
      !failure() && !cancelled()
      && contains(fromJSON(inputs.machines), fromJSON('["X64"]')[0])
      && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/v'))
      && !contains(github.ref, '-draft')

    name: Documents
    runs-on: ['X64', 'het']
    permissions:
      pages: write
      id-token: write

    steps:
      - id: book
        name: Book
        uses: actions/deploy-pages@v4

  containers:
    if: >
      !failure() && !cancelled()
      && inputs.machines
      && inputs.docker_repo != ''
      && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/v'))
      && !contains(github.ref, '-draft')

    name: Containers
    runs-on: ${{matrix.machine}}
    permissions: write-all
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        bake_target: ${{fromJSON('["github", "dockerhub"]')}}
        cargo_profile: ${{fromJSON(inputs.cargo_profiles)}}
        rust_toolchain: ${{fromJSON(inputs.rust_toolchains)}}
        feat_set: ${{fromJSON(inputs.feat_sets)}}
        sys_name: ${{fromJSON(inputs.sys_names)}}
        sys_version: ${{fromJSON(inputs.sys_versions)}}
        rust_target: ${{fromJSON(inputs.rust_targets)}}
        sys_target: ${{fromJSON(inputs.sys_targets)}}
        machine: ${{fromJSON(inputs.machines)}}
        exclude: ${{fromJSON(inputs.excludes)}}
        include: ${{fromJSON(inputs.includes)}}

    steps:
      - name: GitHub Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_token }}

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.dockerhub_token }}

      - name: Bake
        env:
          bake_target: ${{matrix.bake_target}}
          cargo_profile: ${{matrix.cargo_profile}}
          rust_toolchain: ${{matrix.rust_toolchain}}
          rust_target: ${{matrix.rust_target}}
          feat_set: ${{matrix.feat_set}}
          sys_name: ${{matrix.sys_name}}
          sys_version: ${{matrix.sys_version}}
          sys_target: ${{matrix.sys_target}}
          machine: ${{matrix.machine}}
          acct: ${{github.actor}}
          repo: ${{github.repository}}
          docker_repo: ${{inputs.docker_repo}}
          docker_tag_preview: ${{ matrix.cargo_profile == 'release' && matrix.feat_set == 'all' && matrix.sys_target == 'x86_64-linux-gnu' && contains(github.ref, 'refs/tags/v') }}
          docker_tag_latest: ${{ matrix.cargo_profile == 'release' && matrix.feat_set == 'all' && matrix.sys_target == 'x86_64-linux-gnu' && contains(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc') }}

        run: |
          docker/bake.sh "${{matrix.bake_target}}"
